name: Infracost
description: Show cloud cost estimate changes for Terraform in pull requests.
author: infracost
branding:
  icon: trending-up
  color: yellow
inputs:
  path:
    description: Path to the Terraform code directory or JSON/plan file.
    required: false
  terraform_plan_flags:
    description: Flags to pass to the 'terraform plan' command.
    required: false 
  percentage_threshold:
    description: The absolute percentage threshold that triggers a pull request comment with the diff. Defaults to 0, meaning that a comment is posted if the cost estimate changes. For example, set to 5 to post a comment if the cost estimate changes by plus or minus 5%.
    required: false
    default: 0
  usage_file:
    description: Path to Infracost usage file that specifies values for usage-based resources.
    required: false
outputs:
  master_monthly_cost:
    description: The master branch's monthly cost estimate.
  pull_request_monthly_cost:
    description: The pull request's monthly cost estimate.
runs:
  using: docker
  image: docker://infracost/infracost:test # Use a specific version instead of latest if locking is preferred
  args:
    - ${{ inputs.path }}
    - ${{ inputs.terraform_plan_flags }}
    - ${{ inputs.percentage_threshold }}
    - ${{ inputs.usage_file }}

