name: Infracost
description: Show cloud cost estimate changes for Terraform in pull requests.
author: infracost
branding:
  icon: trending-up
  color: yellow
inputs:
  terraform_json_file:
    description: Path to Terraform plan JSON file.
    required: false
  terraform_plan_file:
    description: Path to Terraform plan file relative to 'terraform_dir'. Requires 'terraform_dir' to be set.
    required: false
  terraform_use_state:
    description: Use Terraform state instead of generating a plan (default is false).
    required: false
    default: false
  terraform_dir:
    description: Path to the Terraform code directory (default is current working directory).
    required: false
  terraform_plan_flags:
    description: Flags to pass to the 'terraform plan' command.
    required: false 
  percentage_threshold:
    description: The absolute percentage threshold that triggers a pull request comment with the diff. Defaults to 0, meaning that a comment is posted if the cost estimate changes. For example, set to 5 to post a comment if the cost estimate changes by plus or minus 5%.
    required: false
    default: 0
  pricing_api_endpoint:
    description: Specify an alternate Cloud Pricing API URL (default is https://pricing.api.infracost.io).
    required: false
  usage_file:
    description: Path to Infracost usage file that specifies values for usage-based resources.
    required: false
outputs:
  master_monthly_cost:
    description: The master branch's monthly cost estimate.
  pull_request_monthly_cost:
    description: The pull request's monthly cost estimate.
runs:
  using: docker
  image: docker://infracost/infracost:latest # Use a specific version instead of latest if locking is preferred
  args:
    - ${{ inputs.terraform_json_file }}
    - ${{ inputs.terraform_plan_file }}
    - ${{ inputs.terraform_use_state }}
    - ${{ inputs.terraform_dir }}
    - ${{ inputs.terraform_plan_flags }}
    - ${{ inputs.percentage_threshold }}
    - ${{ inputs.pricing_api_endpoint }}
    - ${{ inputs.usage_file }}

